server:
  port: 8887
  servlet:
    context-path: /spring-boot-template
spring:
  application:
    name: spring-boot-template
  profiles:
    active: dev
#-----------------------------------DAO层-mybatis-2/2[开始]-----------------------------------------------
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

